version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: doc_manager_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Веб-інтерфейс Jaeger
      - "4317:4317"   # OpenTelemetry gRPC порт
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  pgdata:
